### ISSUE TITLE
Update screenshots for "new" UI

### ISSUE THREAD

**Issue by lfaraone** [zulip/zulip.github.io#1]
@allenrabinovich updated the Zulip UI in February 2014. However, we're still showing screenshots of the old UI.

It'd be nice to move away from images entirely and just embed the Zulip CSS, but I don't know if our CSS is sufficiently modular for that.

Related bug: zulip/zulip#599 (should probably be fixed first)

**Comment by gureks** [comment]
Hey @lfaraone 
I'm just starting to contribute here. 
Is this issue still active? If yes, can you elaborate a bit, please?

**Comment by lfaraone** [comment]
Closing in favour of tracking in zulip/zulip#599
