### ISSUE TITLE
Footer needs to be added

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip.github.io#4]
@timabbott Do you think a good footer needs to be added here. Also docs on zulip.org and zulip.com/hello is slightly different. I am not sure it's intentional or not updated.

**Comment by timabbott** [comment]
Yeah, the zulip.org / zulip.com/hello divergence isn't great.  The zulip.org version is I think the newer version and thus probably better (let me know if you think there's things better in zulip.com, though!).  I made an attempt at merging the copy at least a couple months ago, but likely didn't catch everything.

We have a similar issue where README.prod.md is now much more detailed than zulip.org/server.html, and it might make sense to eliminate server.html and just link directly to README.prod.md (possibly migrating to our ReadTheDocs instance) to address that divergence.

What are you thinking should go into a footer on zulip.org?

**Comment by akashnimare** [comment]
I think zulip.org version is better. I'll be sending a PR to fix this.
Yes, we should eliminate server.html and link it to Zulip rtd instance that will keep the things updated.(Let me know what I can do in this)
I was thinking to add a minimal footer which will contain Copyright 2013-2016 Dropbox, Inc and may be some other links like Downloads, Integration, legal etc.

**Comment by akashnimare** [comment]
@timabbott Here is a minimal footer. Let me know what do you think?
![zulip](https://cloud.githubusercontent.com/assets/2263909/14510412/ecbe52c0-01ee-11e6-9cc4-1b4b438c1771.png)

**Comment by brainwane** [comment]
@akashnimare A few suggestions:

* You might want to also link to Zulip's presence on social media (Twitter/Facebook).
* A "Support" link, or a direct link to https://github.com/zulip/zulip/issues/new with text like "Report a Bug", might be a good idea.

Those are suggestions I think are nearly definitely good ideas. Here are two ideas that I am less certain about:

* If it's possible to have a small, unobtrusive but visible "build status" indicator reflecting the [Travis CI build status](https://travis-ci.org/zulip/zulip), I think that would be cool.
* I personally would prefer that the copyright notice also specifically mention that "Zulip is released under the Apache license" after, or instead of, the "all rights reserved" disclaimer.

**Comment by brainwane** [comment]
@akashnimare I think a footer like this would help with the part of (zulip/zulip#668) where we want to create better navigation on Zulip.org to make content easier to discover -- do you think you'll be working on that anytime soon? Thanks.

**Comment by akashnimare** [comment]
@brainwane I am currently into other [stuffs](https://github.com/WebDevLabs-SVNIT/InOut3). But I'll be happy to give my input on this. Meanwhile could you make a quick mockup of the footer? This way we will have more clear idea.

**Comment by timabbott** [comment]
Zulip doesn't currently have a Twitter/Facebook presence, so we may need to leave that off.  I like the "Report an issue" link idea.

I think the Travis CI build status isn't super interesting to most folks (failures are basically all going to bet transient flakes), but yeah adding an Apache license mention would be good.

**Comment by lfaraone** [comment]
On 19 May 2016 at 03:11, Tim Abbott <notifications@github.com> wrote:
>
> I think the Travis CI build status isn't super interesting to most folks
> (failures are basically all going to bet transient flakes), but yeah adding
> an Apache license mention would be good.
>

Yes, but its a signal that we have tests and care about it being green :)

**Comment by timabbott** [comment]
Fair enough; I have no objection to adding it then (though we already have on on GitHub) :)

I've actually been meaning to add one of those coverage badges to the Zulip GitHub page as well, since our test coverage is like 79%, which I think is something to brag about for a project our size :)

**Comment by timabbott** [comment]
(and that's actually just backend test coverage; it's probably higher if you include frontend too!)

**Comment by brainwane** [comment]
We'll want to link to twitter.com/zuliposs and to the new blog.

**Comment by brainwane** [comment]
The new blog: http://blog.zulip.org/

Twitter: http://twitter.com/zuliposs

**Comment by brainwane** [comment]
From conversation in [the developers' Zulip realm](https://zulip.tabbott.net/#narrow/stream/frontend/subject/footer/near/40037) -

The Zulip.org website is about the open source project -- in contrast to http://zulipchat.com/ which is about the service hosted by Kandra Labs (the company). So it's meant to help out open source contributors who might want to contribute to Zulip (or tell their friends about it, etc.), companies or open source projects or other organizations that want to self-host Zulip installations, existing Zulip contributors/botmakers/users who want to know about recent and upcoming plans...

This makes me think it would be a good idea to link to this very realm (zulip.tabbott.net) and the [roadmap](https://zulip.readthedocs.io/en/latest/roadmap.html) in addition to the stuff people have already mentioned in that GitHub issue.

I believe @alanaschueroff is interested in working on this.

**Comment by alanaschueroff** [comment]
I'm working on it right now, I would send the first draft pretty soon.

**Comment by brainwane** [comment]
@alanaschueroff how's this going?

**Comment by deekshaarul** [comment]
I would like to work on this too. Can I collaborate with @alanaschueroff for this?

**Comment by brainwane** [comment]
@deekshaarul Yes, that sounds like a good idea! If she's put a work-in-progress branch up at her GitHub fork, it's probably a good idea to look at it. You can ping @alanaschueroff via Zulip; if she doesn't reply within about 4-5 days, then you can go ahead and work on it yourself without waiting for her.

**Comment by jajodiaraghav** [comment]
@deekshaarul Can i work on this issue or are you working on it currently?

**Comment by brainwane** [comment]
@jajodiaraghav Since @deekshaarul has not responded yet, I think it is fine for you to work on it.

**Comment by timabbott** [comment]
Fixed via #24.
